name: Github Actions Demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 it's workin innit?"
      - uses: actions/checkout@v3
      - run: npm ci